/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `kotlin-dsl`  // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    kotlin("jvm") version "1.8.10"
}

/*
repositories {
    mavenCentral()
    gradlePluginPortal()
}*/

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10")
}

val xvmVersion = libs.versions.xvm.get()
println("XVM Version: $xvmVersion")
