/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `kotlin-dsl`
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
    // Support publishing an artefact for XVM, to local ore remote repos
    `maven-publish`
    // Support convention plugins written in Kotlin. They are scripts in 'src/main/kotlin' that automatically become available as plugins in the main build.    `kotlin-dsl`
    kotlin("jvm") version "1.8.10"
}


gradlePlugin {
    plugins {
        val xtcLang by plugins.creating {
            id = "xtc-lang-plugin"
            implementationClass = "org.xvm.XtcLangPlugin"
        }
    }
}


dependencies {
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10")
}

val xvmVersion = libs.versions.xvm.get()
println("XVM Version: $xvmVersion")
